export const cars = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    year: 2021,
    seats: 5,
    type: "compact",
    pricePerDay: 6000,
    image: "/cars/toyota_corolla.svg",
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2022,
    seats: 5,
    type: "compact",
    pricePerDay: 4000,
    image: "/cars/honda_civic.svg",
  },
  {
    id: 3,
    make: "Ford",
    model: "Escape",
    year: 2021,
    seats: 5,
    type: "suv",
    pricePerDay: 7000,
    image: "/cars/ford_escape.svg",
  },
  {
    id: 4,
    make: "BMW",
    model: "3 Series",
    year: 2020,
    seats: 5,
    type: "compact",
    pricePerDay: 8900,
    image: "/cars/bmw_3series.svg",
  },
  {
    id: 5,
    make: "Audi",
    model: "A4",
    year: 2019,
    seats: 5,
    type: "compact",
    pricePerDay: 10000,
    image: "/cars/audi_a4.svg",
  },
  {
    id: 6,
    make: "Suzuki",
    model: "Grande Vitara",
    year: 2023,
    seats: 5,
    type: "Hybrid SUV",
    pricePerDay: 12000,
    image: "/cars/tesla_model3.svg",
  },
  {
    id: 7,
    make: "Mercedes",
    model: "C 200",
    year: 2021,
    seats: 5,
    type: "compact",
    pricePerDay: 11000,
    image: "/cars/mercedes_c200.svg",
  },
  {
    id: 8,
    make: "Innova",
    model: "Hycross",
    year: 2024,
    seats: 7,
    type: "MUV",
    pricePerDay: 5800,
    image: "/cars/nissan_altima.svg",
  },
  {
    id: 9,
    make: "Suzuki",
    model: "Ertiga",
    year: 2022,
    seats: 7,
    type: "MUV",
    pricePerDay: 3500,
    image: "/cars/chevy_malibu.svg",
  },
  {
    id: 10,
    make: "Scoorpio",
    model: "N",
    year: 2022,
    seats: 7,
    type: "SUV",
    pricePerDay: 7500,
    image: "/cars/kia_stinger.svg",
  },
  {
    id: 11,
    make: "Hyundai",
    model: "Sonata",
    year: 2021,
    seats: 5,
    type: "sedan",
    pricePerDay: 6200,
    image: "/cars/hyundai_sonata.svg",
  },
  {
    id: 12,
    make: "scoorpio",
    model: "classic S11",
    year: 2023,
    seats: 5,
    type: "suv",
    pricePerDay: 4500,
    image: "/cars/subaru_outback.svg",
  },
  {
    id: 13,
    make: "Mahindra",
    model: "THAR",
    year: 2022,
    seats: 5,
    type: "suv",
    pricePerDay: 4000,
    image: "/cars/mazda_cx5.svg",
  },
  {
    id: 14,
    make: "Suzuki",
    model: "Baleno",
    year: 2022,
    seats: 5,
    type: "compact",
    pricePerDay:2500,
    image: "/cars/vw_golf.svg",
  },
  {
    id: 15,
    make: "TATA",
    model: "Harrier",
    year: 2023,
    seats: 5,
    type: "suv",
    pricePerDay: 4200,
    image: "/cars/jeep_cherokee.svg",
  },
  {
    id: 16,
    make: "Hyundai",
    model: "Verna",
    year: 2025,
    seats: 5,
    type: "sedan",
    pricePerDay: 5500,
    image: "/cars/toyota_camry.svg",
  },
  {
    id: 17,
    make: "Hundai",
    model: "Creta",
    year: 2024,
    seats: 5,
    type: "Suv",
    pricePerDay: 5300,
    image: "/cars/honda_accord.svg",
  },
  {
    id: 18,
    make: "Jeep",
    model: "Compass",
    year: 2022,
    seats: 5,
    type: "Suv",
    pricePerDay: 6000,
    image: "/cars/ford_mustang.svg",
  },
  {
    id: 19,
    make: "Jeep",
    model: "wrangler",
    year: 2019,
    seats: 5,
    type: "Suv",
    pricePerDay: 9500,
    image: "/cars/dodge_charger.svg",
  },
];

export const bookings = [];
